apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-external
spec:
  ports:
    - port: 27017
      nodePort: 30093
      protocol: TCP
  selector:
    app: mongo
  type: NodePort