apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: quarkus-camel-k-demo
    app.kubernetes.io/version: "1.0"
  name: quarkus-camel-k-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quarkus-camel-k-demo
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get, list, watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quarkus-camel-k-demo
  namespace: default
roleRef:
  kind: Role
  name: quarkus-camel-k-demo
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: quarkus-camel-k-demo
    namespace: default